openapi: 3.0.0
info:
  title: Extracts Social API
  description: The Extracts Social API.
  contact:
    name: API Support
    url: http://extracts.io/support
    email: support@extracts.io
  version: 1.0.0
servers:
- url: https://cvqtzfgnk3.execute-api.us-east-1.amazonaws.com/Production
  description: Production server
components:
  schemas:
    Status:
      type: object
      properties:
        message:
          type: string
    OfferRedemption:
      type: object
      properties:
        id:
          type: string
          example: "3076dbfa-6f28-11e9-8db4-28cfe91fa8f1"
    CreateOfferRedemption:
      type: object
      required: 
        - teamId
        - offerCode
      properties:
        teamId:
          type: string
          example: "39859716-6f25-11e9-ae22-28cfe91fa8f1"
        offerCode:
          type: string
          example: "SPRING_2019_50_PERCENT_OFF"
        redeemedAt:
          type: string
          format: date-time
        orderId:
          type: string
          example: "O144232334"
        currency:
          type: string
          example: "USD"
        value:
          type: string
          example: "13.33"
          description: The value of the total order
        contentIds:
          type: array
          items:
            type: string
            example: "SKU22242"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
paths:
  /status:
    get:
      description: Gets the status of the server. You can use this to test the API.
      responses:
        '200':
          description: A status response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /offer-redemptions:
    post:
      description: Creates an Offer Redemption. "teamId" and "offerCode" are the only required fields.
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateOfferRedemption'
      responses:
        '200':
          description: Create an Offer Campaign Redemption
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/OfferRedemption'