title: Extracts Social API
description: The Extracts Social API.
contact:
  name: API Support
  url: http://extracts.io/support
  email: support@extracts.io
version: 1.0.0
servers:
- url: https://cvqtzfgnk3.execute-api.us-east-1.amazonaws.com/Production
  description: Production server
components:
  schemas:
    Status:
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
/status:
  get:
    description: Gets the status of the server
    responses:
      '200':
        description: A status response
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Status'